server:
  port: 8080
camel:
  springboot:
    name: ServicesRest
management:
  port: 8081
endpoints:
  enabled: false
  health:
    enabled: true
simplerouter:
  callTimeoutPeriod: 10s
  api:
    path: '/camel'
